### ISSUE TITLE
App crashes when clicking on ticket - java.lang.NullPointerException

### ISSUE THREAD

**Issue by baaguigui** [travelpayouts/white-label-app-android#4]
Hi,
When attempting to click on a ticket in the app, the app crashes and the following error appears in the logs:

`FATAL EXCEPTION: main
Process: com.travelapp.debug, PID: 10073
java.lang.NullPointerException
	at com.travelapp.sdk.flights.ui.builders.i.a(TicketCardBuilder.kt:5335)
	at com.travelapp.sdk.flights.ui.builders.i.a(TicketCardBuilder.kt:3)
	at com.travelapp.sdk.flights.ui.viewmodels.i0.a(TicketCardViewModel.kt:209)
	at com.travelapp.sdk.flights.ui.viewmodels.i0.a(TicketCardViewModel.kt:1)
	at com.travelapp.sdk.flights.ui.viewmodels.i0$h.invokeSuspend(TicketCardViewModel.kt:20)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a23b036, Dispatchers.Main.immediate]
`

I would appreciate any assistance in resolving this issue.

**Comment by tpsupport** [comment]
Hi,

Sorry for the delayed response.
Our developers are already investigating the issue. We will inform you once there are updates. Sorry for the inconvenience caused.
