### ISSUE TITLE
Crash due to AdMob initialization

### ISSUE THREAD

**Issue by baaguigui** [travelpayouts/white-label-app-android#9]
Hi,
I am experiencing a crash when trying to run the app. The app shuts down unexpectedly during initialization.

The issue seems to be related to AdMob initialization, but I do not intend to use ads in this application.

The following error appears in the logs:

`FATAL EXCEPTION: main
Process: com.travelapp.debug, PID: 17705
java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 

******************************************************************************
* Invalid application ID. Follow instructions here:                          *
* https://googlemobileadssdk.page.link/admob-android-update-manifest         *
* to find your app ID.                                                       *
* Google Ad Manager publishers should follow instructions here:              *
* https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
******************************************************************************

	at android.app.ActivityThread.installProvider(ActivityThread.java:7770)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7276)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6983)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: java.lang.IllegalStateException: 

******************************************************************************
* Invalid application ID. Follow instructions here:                          *
* https://googlemobileadssdk.page.link/admob-android-update-manifest         *
* to find your app ID.                                                       *
* Google Ad Manager publishers should follow instructions here:              *
* https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
******************************************************************************

	at com.google.android.gms.ads.internal.client.zzek.attachInfo(com.google.android.gms:play-services-ads-lite@@23.0.0:15)
	at com.google.android.gms.ads.MobileAdsInitProvider.attachInfo(com.google.android.gms:play-services-ads-lite@@23.0.0:1)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7765)
	... 11 more
`

Please provide guidance on how to completely disable AdMob or remove its dependencies from the project configuration, as ads are not needed in this app.

**Comment by tpsupport** [comment]
Hello,

It seems that the issue might be due to an invalid application ID and a test bundle ID (com.travelapp) being specified. Could you please verify that both the application ID and bundle ID are correct?

If you still encounter any issues, please don't hesitate to reach out to us via email at [support@travelpayouts.com](mailto:support@travelpayouts.com).

**Comment by baaguigui** [comment]
Hi,

Yes, I have confirmed that both the application ID and the bundle ID are correct.

I noticed that the app works correctly when I add the google_admob_app_id, but when I remove the advertising{ } block with all the values ​​inside it from the app_config.json file, the app crashes and the same error appears.

Please note that I do not want to use ads in the app. Is there a way to completely disable AdMob or remove its dependency properly?

Thank you for your support.

**Comment by tpsupport** [comment]
Unfortunately, it's not possible to remove the line entirely from the file at the moment. For the `google_admob_app_id` field, please insert your AdMob ID from your AdMob account. This issue will be fixed in future updates.
